image: python:latest

stages:
  - scrape

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V # Print out python version for debugging
  - pip install -r requirements.txt

scrape:
  stage: scrape
  script:
  - python sigmalive-rss-feed-miner/feedminer.py
  artifacts:
    paths:
    - "*.json"
